COLUMN_MAPPING = {
    "admisión": {
        "studentNames": "Nombres de Estudiante",
        "studentFirstSurname": "Primer Apellido del Estudiante",
        "studentSecondSurname": "Segundo Apellido del Estudiante",
        "studentGender": "Género del Estudiante",
        "studentDob": "Fecha de Nacimiento del Estudiante",
        "enteringYear": "Año de Ingreso",
        "studentStreetAddress": "Dirección del Estudiante",
        "studentCity": "Ciudad del Estudiante",
        "studentPostalCode": "Código Postal del Estudiante",
        "studentCountry": "País del Estudiante",
        "relationToStudent": "Relación con el Estudiante",
        "guardianFirstName": "Primer Nombre del Representante",
        "guardianSecondName": "Segundo Nombre del Representante",
        "guardianLastNames": "Apellidos del Representante",
        "guardianStreetAddress": "Dirección del Representante",
        "guardianCity": "Ciudad del Representante",
        "guardianPostalCode": "Código Postal del Representante",
        "guardianCountry": "País del Representante",
        "guardianHomePhone": "Teléfono de Casa del Representante",
        "guardianMobilePhone": "Teléfono Móvil del Representante",
        "guardianEmail": "Correo Electrónico del Representante",
    },
    "contacto": {
        "name": "Nombre",
        "phone": "Teléfono",
        "subject": "Asunto",
        "message": "Mensaje",
    },
}
