const countryOptions = [
  { value: "AR", label: "Argentina" },
  { value: "BR", label: "Brasil" },
  { value: "CL", label: "Chile" },
  { value: "CO", label: "Colombia" },
  { value: "CR", label: "Costa Rica" },
  { value: "CU", label: "Cuba" },
  { value: "DO", label: "República Dominicana" },
  { value: "EC", label: "Ecuador" },
  { value: "SV", label: "El Salvador" },
  { value: "GT", label: "Guatemala" },
  { value: "HN", label: "Honduras" },
  { value: "MX", label: "México" },
  { value: "NI", label: "Nicaragua" },
  { value: "PA", label: "Panamá" },
  { value: "PY", label: "Paraguay" },
  { value: "PE", label: "Perú" },
  { value: "PR", label: "Puerto Rico" },
  { value: "RD", label: "República Dominicana" },
  { value: "UY", label: "Uruguay" },
  { value: "VE", label: "Venezuela" },
  { value: "US", label: "Estados Unidos" },
  { value: "ES", label: "España" },
  { value: "FR", label: "Francia" },
  { value: "IT", label: "Italia" },
  { value: "GB", label: "Reino Unido" },
  { value: "DE", label: "Alemania" },
  { value: "PT", label: "Portugal" },
  { value: "RU", label: "Rusia" },
  { value: "CN", label: "China" },
  { value: "IN", label: "India" },
  { value: "JP", label: "Japón" },
  { value: "KR", label: "Corea del Sur" },
  { value: "AU", label: "Australia" },
  { value: "CA", label: "Canadá" },
  { value: "MX", label: "México" },
  { value: "BR", label: "Brasil" },
  { value: "AR", label: "Argentina" },
  { value: "CL", label: "Chile" },
  { value: "PE", label: "Perú" },
  { value: "CO", label: "Colombia" },
  { value: "VE", label: "Venezuela" },
  { value: "PA", label: "Panamá" },
  { value: "PY", label: "Paraguay" },
  { value: "HN", label: "Honduras" },
  { value: "BO", label: "Bolivia" },
  { value: "EC", label: "Ecuador" },
  { value: "SV", label: "El Salvador" },
  { value: "GT", label: "Guatemala" },
  { value: "DO", label: "República Dominicana" },
  { value: "CU", label: "Cuba" },
  { value: "NG", label: "Nigeria" },
  { value: "KE", label: "Kenia" },
  { value: "ZA", label: "Sudáfrica" },
  { value: "EG", label: "Egipto" },
  { value: "AE", label: "Emiratos Árabes Unidos" },
  { value: "IN", label: "India" },
  { value: "SG", label: "Singapur" },
  { value: "MY", label: "Malasia" },
  { value: "ID", label: "Indonesia" },
  { value: "TH", label: "Tailandia" },
  { value: "PH", label: "Filipinas" },
  { value: "PK", label: "Pakistán" },
  { value: "SA", label: "Arabia Saudita" },
  { value: "KR", label: "Corea del Sur" },
  { value: "VN", label: "Vietnam" },
  { value: "TW", label: "Taiwán" },
  { value: "TR", label: "Turquía" },
  { value: "GR", label: "Grecia" },
  { value: "SE", label: "Suecia" },
  { value: "NO", label: "Noruega" },
  { value: "FI", label: "Finlandia" },
  { value: "DK", label: "Dinamarca" },
  { value: "IS", label: "Islandia" },
  { value: "BE", label: "Bélgica" },
  { value: "NL", label: "Países Bajos" },
  { value: "LU", label: "Luxemburgo" },
  { value: "AT", label: "Austria" },
  { value: "CH", label: "Suiza" },
  { value: "PL", label: "Polonia" },
  { value: "CZ", label: "República Checa" },
  { value: "SK", label: "Eslovaquia" },
  { value: "HU", label: "Hungría" },
  { value: "RO", label: "Rumanía" },
  { value: "BG", label: "Bulgaria" },
  { value: "HR", label: "Croacia" },
  { value: "RS", label: "Serbia" },
  { value: "UA", label: "Ucrania" },
  { value: "BY", label: "Bielorrusia" },
  { value: "EE", label: "Estonia" },
  { value: "LV", label: "Letonia" },
  { value: "LT", label: "Lituania" },
  { value: "MD", label: "Moldavia" },
  { value: "AM", label: "Armenia" },
  { value: "GE", label: "Georgia" },
  { value: "AZ", label: "Azerbaiyán" },
  { value: "IQ", label: "Irak" },
  { value: "IL", label: "Israel" },
  { value: "JO", label: "Jordania" },
  { value: "KW", label: "Kuwait" },
  { value: "LB", label: "Líbano" },
  { value: "SY", label: "Siria" },
  { value: "QA", label: "Catar" },
  { value: "BH", label: "Baréin" },
  { value: "OM", label: "Omán" },
  { value: "YE", label: "Yemen" },
];

export default countryOptions;