name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        version: "0.5.18"

    - name: Set up Python
      run: uv python install

    - name: Enable caching
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true

    - name: Package Lambda function
      run: |
        cd backend
        uv export --frozen --no-dev --no-editable -o requirements.txt
        uv pip install --no-installer-metadata --no-compile-bytecode --python-platform x86_64-manylinux2014 --target packages -r requirements.txt
        cd packages
        zip -r ../package.zip .
        cd ..
        zip -r package.zip cevda

    - name: Deploy to AWS Lambda
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: us-east-2
      run: |
        cd backend
        aws lambda update-function-code \
          --function-name email-handler-nonprod \
          --zip-file fileb://package.zip
